# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.12
    - 172.18.0.5
    - 192.168.1.20
    - 192.168.1.254
    - 172.30.33.0/24
    - 172.17.0.0/16
    - 172.18.0.0/16
  # ssl_certificate: keys/fullchain.pem
  # ssl_key: keys/privkey.pem
#  cors_allowed_origins:
#  - https://cast.home-assistant.io

websocket_api:

media_extractor:

rest_command: !include rest_commands.yaml

wake_on_lan:

### INCLUDES ###
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
# alert: !include_dir_merge_named alerts/

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
  media_dirs:
    local: /media

logger:
  default: info
  logs:
    homeassistant.components.smartthings: debug
    bravia_tv: debug 
    homeassistant.components.braviatv: debug

frontend:
  themes: !include_dir_merge_named themes

python_script:

# influxdb:
#   host: 192.168.1.12
#   username: HASS
#   password: !secret influxpass
#   exclude:
#     entity_globs:
#       - glances
#     domains:
#       - automation

# google:
#   client_id: !secret google_cal_id
#   client_secret: !secret google_cal_pass

google_assistant:
  project_id: home--hass
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

# nest:
#   client_id: !secret nest_client_id 
#   client_secret: !secret nest_client_secret
#   project_id: !secret nest_project_id
#   subscriber_id: !secret nest_subscriber_id

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

media_source:

media_player:
  - platform: braviatv_psk
    host: 192.168.1.51
    psk: sony
    mac: !secret bravia_mac
    amp: True
    android: True
    time_format: 12H
    user_labels: True
    name: "Living Room Sony TV"
    
  - platform: mediaroom

  - platform: emby
    host: 192.168.1.12
    api_key: !secret emby_api

# panel_iframe:
#   windy:
#     title: 'Windy'
#     url: 'https://embed.windy.com/embed2.html?lat=56.715&lon=-111.484&detailLat=56.749&detailLon=-111.484&width=650&height=450&zoom=11&level=surface&overlay=rain&product=ecmwf&menu=&message=true&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=true&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1'
#     icon: mdi:weather-partly-snowy


shell_command:
  restart_hass: 'curl http://192.168.1.12:8126/container/Home-Assistant-Core/restart'
  ptz_front_door: 'curl  "http://192.168.1.14:81/admin?camera=LVG&trigger&preset=3&user=HASS&pw=hasspass"'
  ptz_living_room_home: 'curl  "http://192.168.1.14:81/admin?camera=LVG&preset=1&user=HASS&pw=hasspass"'
  ptz_kitchen: 'curl  "http://192.168.1.14:81/admin?camera=LVG&preset=4&user=HASS&pw=hasspass"'


recorder:
  exclude:
    entities:
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.watchman_last_updated


watchman:
  ignored_files:
    # wildcards must be enclosed in quotes!
    # - "*.yaml" # exclude all yaml files from the report (useless)
    - "/.cuttingroom/*" # exclude all files in /config/entities
    # - "*/automations.yaml" # exclude automations.yaml file only

# samsungtv:
#   - host: 192.168.1.80
#     turn_on_action:
#       - service: wake_on_lan.send_magic_packet
#         data:
#           mac: fc:03:9f:9f:4c:6f

weather:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    #latitude: Location latitude
    #longitude: Location longitude
    mode: "hourly"
    name: Fort McMurray Pirate Weather
    

# you can also get a sensor data
sensor:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

mqtt:
  sensor:
    - name: "Washer Status"
      state_topic: "house/washer/status"
    - name: "Washer Last Complete"
      state_topic: "house/washer/time_complete"
    - name: "Washer Last Emptied"
      state_topic: "house/washer/time_emptied"
  binary_sensor:
    - name: "Room Presence"
      state_topic: "house/presence/current_room"
    - name: "Room Presence Last"
      state_topic: "house/presence/last_room"
    - name: "Room Presence 2nd Last"
      state_topic: "house/presence/2nd_last_room"
    - name: "Room Presence 3rd Last"
      state_topic: "house/presence/3rd_last_room"

image_processing:
  # - platform: deepstack_object
  #   ip_address: 192.168.1.12
  #   port: 5000
  #   timeout: 10
  #   save_file_folder: /media/snapshots/
  #   always_save_latest_file: true
  #   save_timestamped_file: True
  #   targets:
  #     - target: person
  #       confidence: 70
  #     - target: dog
  #       confidence: 80
  #   source:
  #     - entity_id: camera.blueiris_doorbell
  #     - entity_id: camera.blueiris_front_yard

  - platform: deepstack_face
    ip_address: 192.168.1.12
    port: 5000
    timeout: 5
    detect_only: False
    save_file_folder: /media/snapshots/
    save_timestamped_file: True
    save_faces: True
    save_faces_folder: /media/faces/
    show_boxes: false
    source:
      - entity_id: camera.blueiris_doorbell
      - entity_id: camera.blueiris_front_yard

switch:
  - platform: broadlink
    mac: c8:f7:42:16:b1:c7
    switches:
      - name: Basement Samsung TV
        command_on: JgBeAAABJpQTEhQRFDUVEBQRFQ8VEBUQFTQVNRUQFDUVNRQ1FTUVNBQRFBEVEBQ1GQ0RExQQFRAVNRQ1FTUUEBQ2FDUUNhQ1FKgFAAKKCAAB5QABJkoVAAxRAAEoSBUADQUAAAAAAAAAAAAA
        command_off: JgBeAAABJpQTEhQRFDUVEBQRFQ8VEBUQFTQVNRUQFDUVNRQ1FTUVNBQRFBEVEBQ1GQ0RExQQFRAVNRQ1FTUUEBQ2FDUUNhQ1FKgFAAKKCAAB5QABJkoVAAxRAAEoSBUADQUAAAAAAAAAAAAA
  - platform: broadlink
    mac: c8:f7:42:16:b1:c7
    switches:
      - name: Basement Heater
        command_on: JgDIACoMKg0PKCgPKA8NKg0qDSsOKQ8oDyko7CgPKA8NKigPKQ4NKg0rDSoPKQ0qDSopAAEQKwwrChEpKg0qDQ8oDygPKQ8oDygPKSrqKwwpDw8oKwwrDBAoECcQJxAoDygPKCsAAQ4rDCsMDykqDSoKEigPKQ8oDygQKA8oK+ouCCwMDygrDSsMDygQJxAoDSoQKA8oLAABCS8NKg0PKCoNKg0PKA8pDyQTKA8pDygt6CgPKA8NKi0KKQ4NKw0qDSoNKg4qDygqAA0F
        command_off: JgDIACoMKg0PKCgPKA8NKg0qDSsOKQ8oDyko7CgPKA8NKigPKQ4NKg0rDSoPKQ0qDSopAAEQKwwrChEpKg0qDQ8oDygPKQ8oDygPKSrqKwwpDw8oKwwrDBAoECcQJxAoDygPKCsAAQ4rDCsMDykqDSoKEigPKQ8oDygQKA8oK+ouCCwMDygrDSsMDygQJxAoDSoQKA8oLAABCS8NKg0PKCoNKg0PKA8pDyQTKA8pDygt6CgPKA8NKi0KKQ4NKw0qDSoNKg4qDygqAA0F
