blueprint:
  name: Timed Motion-activated Light
  description: Turn on a light when motion is detected within a certain time contraint.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    light_strength:
      name: Light Strength
      description: Light level for configured lamps on trigger.
      default: 50
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 1.0
    time_from:
      name: Timeslot from
      default: '22:00:00'
      selector:
        time: {}
    time_to:
      name: Timeslot to
      default: 07:00:00
      selector:
        time: {}
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
  source_url: https://gist.github.com/rvdlee/d489f0e433c865b93da8c1da72be5b8d
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input 'motion_entity'
  from: 'off'
  to: 'on'
condition:
- condition: time
  after: !input 'time_from'
  before: !input 'time_to'
action:
- service: light.turn_on
  target: !input 'light_target'
  data:
    brightness_pct: !input 'light_strength'
- wait_for_trigger:
    platform: state
    entity_id: !input 'motion_entity'
    from: 'on'
    to: 'off'
- delay: !input 'no_motion_wait'
- service: light.turn_off
  target: !input 'light_target'
