
sensor:
  - platform: feedparser
    name: Canada Weather Alerts
    feed_url: 'https://weather.gc.ca/rss/warning/ab-20_e.xml'
    date_format: '%Y-%m-%dT%H:%M:%SZ'
    scan_interval: 60

  - platform: template
    sensors:
      #sensor that only counts active alerts
      canada_weatheralerts_active_alerts:
        friendly_name: Weather Alerts Active
        entity_id:
          - sensor.canada_weather_alerts
          # - sensor.time_hour
        unit_of_measurement: Alerts
        icon_template: mdi:alert-rhombus
        value_template: >-
          {% set alerts_active = namespace(count=0) %}
          {% if (state_attr('sensor.canada_weather_alerts', 'entries')) %}
            {% for entry in state_attr('sensor.canada_weather_alerts', 'entries') %}
              {% if ' ended' not in entry['summary'].lower() and 'no watches or warnings in effect' not in entry['summary'].lower() %}
                {% set alerts_total.count = alerts_total.count + 1 %} 
              {% endif %}
            {% endfor %}
          {% endif %}
          {{ alerts_active.count }}

      #sensor that counts all active and ended/expired alerts
      canada_weatheralerts_total_alerts:
        friendly_name: Weather Alerts Total
        entity_id:
          - sensor.canada_weather_alerts
          # - sensor.time_hour
        unit_of_measurement: Alerts
        icon_template: mdi:alert-rhombus
        value_template: >-
          {% set alerts_total = namespace(count=0) %}
          {% if (state_attr('sensor.canada_weather_alerts', 'entries')) %}
            {% for entry in state_attr('sensor.canada_weather_alerts', 'entries') %}
              {% if 'no watches or warnings in effect' not in entry['summary'].lower() %}
                {% set alerts_total.count = alerts_total.count + 1 %} 
              {% endif %}
            {% endfor %}
          {% endif %}
          {{ alerts_total.count }}