sensor:
  - platform: emby_upcoming_media
    api_key: !secret emby_api
    user_id: !secret emby_id
    host: 192.168.1.12
    port: 8096
    ssl: false
    max: 10
    use_backdrop: true
    include:
      - Movies
      - TV shows

  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api
    host: 192.168.1.12
    port: 8989
    days: 3
    ssl: false
    max: 10

  - platform: radarr_upcoming_media
    api_key: !secret radarr_api
    host: 192.168.1.12
    port: 7878
    days: 14
    ssl: false
    theaters: false
    max: 10

  - platform: integration
    source: sensor.computer_monitor_power_meter
    name: computer_monitor_energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.humidifier_power_meter
    name: humidifier_energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.lava_lamp_power_meter
    name: lava_lamp_energy_spent
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.washer_power_meter
    name: washer_energy_spent
    unit_prefix: k
    round: 2

##  - platform: mqtt
##    name: "Ram Torque"
##    state_topic: "devices/ram1500/torque"
##    value_template: "{{ state_attr('sensor.ram_torque','GPS Time') }}"
##    jason_attributes_topic: "devices/ram1500/torque"

#  - platform: pushbullet
#    api_key: !secret pushbullet_api


  - platform: template
    sensors:
      van_dte:
        friendly_name: "Van DTE"
        unit_of_measurement: 'Km'
        value_template: "{{ state_attr('sensor.fordpass_fuel','distanceToEmpty') }}"
        icon_template: mdi:gas-station
      big_d_array_total_space:
        friendly_name: "Array Total Space"
        unit_of_measurement: 'TB'
        value_template: "{{ state_attr('binary_sensor.big_d_server','arrayTotalSpace') }}"
      big_d_array_free_space:
        friendly_name: "Array Free Space"
        unit_of_measurement: 'TB'
        value_template: "{{ state_attr('binary_sensor.big_d_server','arrayFreeSpace') }}"
      big_d_array_used_space:
        friendly_name: "Array Used Space"
        unit_of_measurement: 'TB'
        value_template: "{{ state_attr('binary_sensor.big_d_server','arrayUsedSpace') }}"
      big_d_cache_total_space:
        friendly_name: "Cache Total Space"
        unit_of_measurement: 'GB'
        value_template: "{{ state_attr('binary_sensor.big_d_server','cacheTotalSpace') }}"
      big_d_cache_free_space:
        friendly_name: "Cache Free Space"
        unit_of_measurement: 'GB'
        value_template: "{{ state_attr('binary_sensor.big_d_server','cacheFreeSpace') }}"
      big_d_cache_used_space:
        friendly_name: "Cache Used Space"
        unit_of_measurement: 'GB'
        value_template: "{{ state_attr('binary_sensor.big_d_server','cacheUsedSpace') }}"
      fordpass_oil_actual:
        friendly_name: "Oil Life"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.fordpass_oil','OilLifeActual') }}"

      dayoftheweek:
        value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
      month:
        value_template: "{{ ['January','February','March','April','May','June','July','August','September','October','November','December'][now().month-1] }}"
      dateofthemonth:
        value_template: "{{ ['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21th','22th','23th','24th','25th','26th','27th','28th','29th','30th','31th' ][ now().day-1] }}"

  - platform: deluge
    host: 192.168.1.12
    username: !secret deluge_user
    password: !secret deluge_pass
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
      
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

binary_sensor:
  # - platform: torque
  #   name: Tristyn's Ram
  #   email: tristynrusselo@gmail.com

  - platform: tod
    name: Daylight
    after: sunrise
    before: sunset

  - platform: tod
    name: Twilight
    after: sunset
    before: sunrise

  - platform: tod
    name: Morning
    after: '04:00'
    before: '09:00'

  - platform: tod
    name: Day
    after: '09:00'
    before: '19:00'

  - platform: tod
    name: Evening
    after: '19:00'
    before: '21:00'

  - platform: tod
    name: Night
    after: '21:00'
    before: '04:00'